### ISSUE TITLE
Discussion on capturing required functionalities within package 

### ISSUE THREAD

**Issue by NMoghaddam** [GeoscienceAustralia/HiQGA.jl#12]
Following an early discussion with Yusen, I captured a few items as follows that it is better to be discussed in a meeting. 
- Having the `read_survey_file` function as a more generic function that deals with any type of input dataset. May be similar approach in our previously developed scripts could be adopted here, i.e. `*.stm` file that basically extracts important information from input data to feed into inversion code.  In this way, we can handle both SkyTEM, Tempest etc. in a harmonised approach. 
- As an open-source code, the analyst/developer might need to add/change a few components of the function. The current version is structured in a way that it is a bit difficult to navigate to where a particular function is located. 
- Two plots as shown here are not representative enough. For instance, the high altitude noise for HM and LM is better to be displayed in a graph way rather than what the left panels show. Having observed and modelled data to better understand the misfit definitely helps. 
![Figure_1](https://user-images.githubusercontent.com/43155679/164353158-320468b4-4ca5-4fa4-ae4c-46ed39a96402.png)
![Figure_5_occ](https://user-images.githubusercontent.com/43155679/164353167-07d0d379-806f-4f76-b1fd-a0282c7a55ca.png)

**Comment by NMoghaddam** [comment]
A few open issues that can be referenced in our discussion are:
- Amplitude inversion plots for TEMPEST
https://github.com/a2ray/transD_GP/issues/18
-Read column names for tempest instead of manually assigning column nos
https://github.com/a2ray/transD_GP/issues/21
- Quit on no improvement in gradient-based 
https://github.com/a2ray/transD_GP/issues/24
- use pmap for processing SkyTEM or Tempest transD plots
https://github.com/a2ray/transD_GP/issues/26

**Comment by a2ray** [comment]
Thanks @yusenley and @NMoghaddam for your feedback. In brief, I will respond here:
- `read_survey_file` exists for each AEM system we can currently handle out of the box, e.g., [here](https://github.com/GeoscienceAustralia/HiQGA.jl/blob/d164fba5dc4a7a80d9a5e180d21085dad64a8bd7/src/SkyTEM1DInversion.jl#L172) and [here](https://github.com/GeoscienceAustralia/HiQGA.jl/blob/d164fba5dc4a7a80d9a5e180d21085dad64a8bd7/src/TEMPEST1DInversion.jl#L549) so in API form and for workflow purposes, this is generic. Each system needs different input fields, and there has to be some way to supply them. Currently, there is an `electronics_halt.jl` or some file which supplies extremely specific fields like waveforms, gate times and high_altitude noise for each system, but again, this is generic to the workflow irrespective of AEM system.
- Users are free to make any modifications they wish to any part of the code as it is under the MIT license! If specific requests are made for any functions, issues can be opened and we can take care of them, or better, still, fork it or branch it and open a pull request! Most functions for a particular geophysical method exist within the enclosing module e.g., for Tempest in [TEMPEST1DInversion.jl](https://github.com/GeoscienceAustralia/HiQGA.jl/blob/d164fba5dc4a7a80d9a5e180d21085dad64a8bd7/src/TEMPEST1DInversion.jl) and the common ones are in [CommonToAll.jl](https://github.com/GeoscienceAustralia/HiQGA.jl/blob/d164fba5dc4a7a80d9a5e180d21085dad64a8bd7/src/CommonToAll.jl)
- If you would like to show AEM forward responses as part of the inverted section, please open a pull request. This will require some familiarity with the forward modeling part of the code, and I encourage you to look [here](https://github.com/GeoscienceAustralia/HiQGA.jl/blob/d164fba5dc4a7a80d9a5e180d21085dad64a8bd7/src/SkyTEM1DInversion.jl#L387) for SkyTEM and [here](https://github.com/GeoscienceAustralia/HiQGA.jl/blob/master/src/TEMPEST1DInversion.jl) for Tempest.

**Comment by yusenley** [comment]
Thanks Ananad, Its clear. Negin has helped me fork a branch so I will work with this.

**Comment by NMoghaddam** [comment]
The links you provided are very helpful @a2ray. Thank you.

**Comment by a2ray** [comment]
No worries, another thing which maybe useful .. the Julia `methods` function to help you discover where functions are ...
for example
```
using HiQGA.transD_GP
methods(transD_GP.getchi2forall)
# 2 methods for generic function "getchi2forall":
[1] getchi2forall(optn_in::HiQGA.transD_GP.OptionsNuisance; nchains, figsize, fsize, alpha, nxticks, gridon) in HiQGA.transD_GP.CommonToAll at /g/data/z67/ar0754/juliadev/HiQGA/src/CommonToAll.jl:263
[2] getchi2forall(opt_in::HiQGA.transD_GP.Options; nchains, figsize, fsize, alpha, nxticks, gridon, omittemp) in HiQGA.transD_GP.CommonToAll at /g/data/z67/ar0754/juliadev/HiQGA/src/CommonToAll.jl:306
```

**Comment by NMoghaddam** [comment]
Cool @a2ray. I tried searching for the location of a couple of items as follows:

```
methods(transD_GP.dfn2hdr)
# 1 method for generic function "dfn2hdr":
[1] dfn2hdr(dfnfile::String) in HiQGA.transD_GP.CommonToAll at /g/data/z67/nfm547/package/HiQGA/src/CommonToAll.jl:1002
methods(transD_GP.read_survey_file)
ERROR: UndefVarError: read_survey_file not defined
```
I even used the following but received the same error.
```
methods(transD_GP.SkyTEM1DInversion.read_survey_file) 
```
