### ISSUE TITLE
Read ASEG-GDF description file

### ISSUE THREAD

**Issue by NMoghaddam** [GeoscienceAustralia/HiQGA.jl#2]
Generate hdr file like GA-AEM produces which looks like
```
1   fiducial
2   line
3   flight
4   datetime
5   date
6   utc_time
.
.
.
```

**Comment by NMoghaddam** [comment]
A function to read the *.dfn file and generate header file in Julia is now available to meet the requirement for the next issue i.e. "using string from header file instead of column number".

**Comment by NMoghaddam** [comment]
closed by https://github.com/a2ray/transD_GP/commit/f403771caf1a2ec33491cd558a6c12120393b070

**Comment by NMoghaddam** [comment]
Unfortunately, cumulative column numbers are required after dumping the TRNS and PROJ records, and getting the number of columns per record from the Fortran numeric specifier just after the first: after the first ;

**Comment by NMoghaddam** [comment]
The additional TRNS, PROJ information in the *.dfn file is filtered out. In the case of having the DATA column in the *.dat file, the changes that @richardt94 did to the dfn2hdr is now handling it quite nicely. I am comfortable closing this issue at this stage. The outcome of the updated version of the `dfn2hdr` function, is a text file that its name is matching with the *.dfn file of particular AEM line survey.

**Comment by NMoghaddam** [comment]
The following plots show the comparison between the soundings resulting from the old and new read_survey_file. 

`Using old read_survey_file`
![Figure_S](https://user-images.githubusercontent.com/43155679/163091590-89ceda14-bb47-431a-9fee-cbbd9b10c076.png)

`Using new read_survey_file`
![Figure_S2](https://user-images.githubusercontent.com/43155679/163091620-f11c7dc2-fa40-4952-8892-539649698cdc.png)

As the plots show, the outcomes are quite similar. 

Numerical comparison also shows negligible difference confirming that the upgrades to the `SKyDEM1DInversion" code within read_survey_file work as we expected. 

**Low Moment - [The noise will decrease with increasing the number of index in soundings]**
`maximum(abs.((soundings[56].LM_data - soundings2[56].LM_data)./soundings[56].LM_data))`
2.8832569271364537e-6
`maximum(abs.((soundings[1].LM_noise - soundings2[1].LM_noise)./soundings[1].LM_noise))`
3.821856010062641e-6
`maximum(abs.((soundings[28].LM_noise - soundings2[28].LM_noise)./soundings[28].LM_noise))`
2.998512602011722e-6
`maximum(abs.((soundings[56].LM_noise - soundings2[56].LM_noise)./soundings[56].LM_noise))`
2.46496171548143e-6
`maximum(abs.((soundings[56].LM_times - soundings2[56].LM_times)./soundings[56].LM_times))`
0.0

**High Moment - [The noise will increase with increasing the number of index in soundings]**
`maximum(abs.((soundings[56].HM_data - soundings2[56].HM_data)./soundings[56].HM_data))`
0.000138374256238566
`maximum(abs.((soundings[1].HM_noise - soundings2[1].HM_noise)./soundings[1].HM_noise))`
6.663130983595906e-5
`maximum(abs.((soundings[28].HM_noise - soundings2[28].HM_noise)./soundings[28].HM_noise))`
6.920547482730497e-5
`maximum(abs.((soundings[56].HM_noise - soundings2[56].HM_noise)./soundings[56].HM_noise))`
0.00010863764836772673
`maximum(abs.((soundings[56].HM_times - soundings2[56].HM_times)./soundings[56].HM_times))`
0.0

**Comment by a2ray** [comment]
Nice! The data and noise are in units of pV so I think we're good with such low differences. Not sure I understand the noise increase with increase in the sounding index number though.

**Comment by NMoghaddam** [comment]
Thanks for the comment. I edited the statements for both low and high moments.
