### ISSUE TITLE
[Bug] constructor for `OptionsNuisance` modifies its own arguments

### ISSUE THREAD

**Issue by richardt94** [GeoscienceAustralia/HiQGA.jl#3]
The function [here](https://github.com/GeoscienceAustralia/HiQGA.jl/blob/529d7fb034a1fedf65f3c26df42248491cf138bf/src/TransD_GP_MCMC.jl#L229) takes an array argument `sdev` which is then bound to a new `OptionsNuisance` struct. On [this line](https://github.com/GeoscienceAustralia/HiQGA.jl/blob/529d7fb034a1fedf65f3c26df42248491cf138bf/src/TransD_GP_MCMC.jl#L285) the array is modified in-place (because it is supposed to represent the width of the proposal distribution as a proportion of the prior bounds on a nuisance). Because array arguments in Julia are passed by reference, this means that the `sdev` array which is passed to the constructor function is silently changed by the function - this is an issue if, for example, an inversion is being performed with the same `sdev` parameters for a number of separate soundings/datasets as those parameters will be silently modified every time an inversion is initialised.

**Comment by richardt94** [comment]
I am about to submit a PR on this, but I've also noted a couple of oddities in the nuisance sampling code that should probably be fixed in the future:

1. Every time a nuisance move is made an entirely new copy of the associated options structure is made. This is wasteful and will slow inversions down, and it appears the only reason it is done is to allow rotating the sampling space according to some supplied covariance matrix.
2. Even if a covariance matrix is not supplied, the code is still calculating "rotated" versions of the prior bounds and using those instead. This reduces the numerical accuracy of the bounds that the sampler is actually using and performs a bunch of unnecessary matrix diagonalisation/multiplication.

**Comment by a2ray** [comment]
We could fix the diagonalisation yes but more than 3 or 4 nuisances aren't feasible to invert anyway ... for these the unnecessary diagonalisation is pretty fast. Agreed there should be a better way, I just didn't want to write a new `oneaxis` move and reused the old one, but it needs an `optn` with rotated bounds.

**Comment by richardt94** [comment]
Yeah I think the linear algebra ops are fairly cheap for a small number of nuisance parameters.

The comment about not being able to sample without rotating to principal components for more than a few nuisance parameters surprises me - MCMC is supposed to be good at producing samples from multi-dimensional distributions, and I did a simple test using [this script](https://gist.github.com/richardt94/bda3c502fe1d24e045a7664ac9a32cf8) to compare Metropolis-Hastings sampling efficiency of a highly-correlated normal distribution with and without rotating the sampling coordinates. Qualitatively, it looks about the same to me:
![original](https://user-images.githubusercontent.com/29562583/161662824-658a5915-c6cb-4311-be67-4bbfc7933045.png)
![rotated](https://user-images.githubusercontent.com/29562583/161662828-7e243253-8e98-4891-87d7-aade47c0d76a.png)
 
Does this mean that if we had 3 or 4 _uncorrelated_ nuisance parameters we would be completely unable to sample them properly?

**Comment by richardt94** [comment]
In any case, once we're ready to progress changes to the nuisance sampler further it's probably best to open a separate issue referencing this one.

**Comment by a2ray** [comment]
No actually,  if there are strong correlations ... unrotated McMC propsals walk on coordinate axes which are not aligned with the correlation directions. This is extremely inefficient. While not apparent in 2 dimensions, 3 or 4 highly correlated parameters are ok, more are problematic. If you use a sampled correlation for say three Tempest nuisances, it is much quicker to converge. That's why the initial synthetics had so much trouble ... but since the forwards were cheap we said may as well sample longer instead of using a sample covariance.  See (this)[https://iopscience.iop.org/article/10.1088/0266-5611/30/11/114018] for a more detailed explanation in the proposal part.
